services:
  ticketing:
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    image: sail-8.4/app
    container_name: ticketing.app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${APP_PORT:-80}:80'
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
      - '${VITE_REVERB_PORT:-8080}:${VITE_REVERB_PORT:-8080}'
    environment:
      WWWUSER: '${WWWUSER}'
      LARAVEL_SAIL: 1
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
      IGNITION_LOCAL_SITES_PATH: '${PWD}'
      SUPERVISOR_PHP_COMMAND: '${SUPERVISOR_PHP_COMMAND:-/usr/bin/php -d variables_order=EGPCS /var/www/html/artisan octane:start --watch --host=0.0.0.0 --port=${APP_PORT:-80}}'
    volumes:
      - '.:/var/www/html'
    networks:
      - ticketing
    depends_on:
      - mysql
  mysql:
      image: 'mysql/mysql-server:8.0'
      container_name: ticketing.database
      ports:
        - '${FORWARD_DB_PORT:-3306}:3306'
      environment:
        MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        MYSQL_ROOT_HOST: '%'
        MYSQL_DATABASE: '${DB_DATABASE}'
        MYSQL_USER: '${DB_USERNAME}'
        MYSQL_PASSWORD: '${DB_PASSWORD}'
        MYSQL_ALLOW_EMPTY_PASSWORD: 1
      volumes:
        - 'ticketing-database:/var/lib/mysql'
        - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
      networks:
        - ticketing
      healthcheck:
        test:
          - CMD
          - mysqladmin
          - ping
          - '-p${DB_PASSWORD}'
        retries: 3
        timeout: 5s
  mailpit:
    image: 'axllent/mailpit:latest'
    container_name: ticketing.mailpit
    ports:
      - '${FORWARD_MAILPIT_PORT:-1025}:1025'
      - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
    networks:
      - ticketing
networks:
  ticketing:
    name: ticketing
    driver: bridge
volumes:
  ticketing-database:
    name: ticketing.database
    driver: local
